const userprofiles = [
    {
        id: 1,
        firstName: 'Luisa',
        lastName: 'Stückelberger',
        isComplete: true,
        description:
            'Im currently homeless looking for a room in the zurich area. 22 and also quite funny',
        biography: '22 y/o student @UZH',
        tags: ['COOKING', 'SPORTS', 'INSTRUMENTS', 'JUWO'],
        pictureReference: [
            'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fHdvbWFuJTIwcHJvZmlsZXxlbnwwfHwwfHw%3D&w=1000&q=80',
            'https://vc-smash.ch/img/asset/YXNzZXRzL3RlYW1mb3Rvcy9ENC0yMDIxLTIyLmpwZWc=?fit=crop-51-34-1&w=1800&h=600&dpr=2&fm=webp&s=58a5b80a46d99ae2bc0cf8dba5ae34c4',
        ],
        matches: ['FLAT#823rsadhfae323'],
        creationDate: '2022-04-20',
        onlineStatus: 'Online',
        birthday: '1999-04-15',
        email: 'luisa@test.com',
        phoneNumber: '0764335622',
        gender: 'Female',
        isSearchingRoom: true,
        isAdvertisingRoom: false,
        moveInDate: '2022-04-21',
        moveOutDate: '',
    },
    {
        id: 2,
        firstName: 'John',
        lastName: 'Stückelberger',
        isComplete: true,
        description:
            "Hi, I'm John, I'm super fun and cool. I am looking for a place to stay for the next 4 weeks since I am only in town for an internship. Love to meet new people and have some fun",
        biography: '22 y/o student @UZH',
        tags: ['COOKING', 'SPORTS', 'INSTRUMENTS', 'JUWO'],
        pictureReference: [
            'https://www.mensjournal.com/wp-content/uploads/mf/1280-selfie.jpg?w=1200&quality=86&strip=all',
            'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bWFsZSUyMHByb2ZpbGV8ZW58MHx8MHx8&auto=format&fit=crop&w=900&q=60',
        ],
        matches: ['FLAT#823rsadhfae323'],
        creationDate: '2022-04-20',
        onlineStatus: 'Online',
        birthday: '1999-04-15',
        email: 'luisa@test.com',
        phoneNumber: '0764335622',
        gender: 'Male',
        isSearchingRoom: true,
        isAdvertisingRoom: false,
        moveInDate: '2022-04-21',
        moveOutDate: '',
    },
    {
        id: 3,
        firstName: 'Marco',
        lastName: 'Stückelberger',
        isComplete: true,
        description:
            "Hi, I'm John, I'm super fun and cool. I am looking for a place to stay for the next 4 weeks since I am only in town for an internship. Love to meet new people and have some fun",
        biography: '22 y/o student @UZH',
        tags: ['COOKING', 'SPORTS', 'INSTRUMENTS', 'JUWO'],
        pictureReference: [
            'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bWFsZSUyMHByb2ZpbGV8ZW58MHx8MHx8&auto=format&fit=crop&w=900&q=60',
            'https://www.mensjournal.com/wp-content/uploads/mf/1280-selfie.jpg?w=1200&quality=86&strip=all',
        ],
        matches: ['FLAT#823rsadhfae323'],
        creationDate: '2022-04-20',
        onlineStatus: 'Online',
        birthday: '1999-04-15',
        email: 'luisa@test.com',
        phoneNumber: '0764335622',
        gender: 'Male',
        isSearchingRoom: true,
        isAdvertisingRoom: false,
        moveInDate: '2022-04-21',
        moveOutDate: '',
    },
];
export default userprofiles;
