//AUTH CONSTANTS for firebase auth calls
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

//USERPROFILE CONSTANTS for backend api calls
export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';

export const POST_USERPROFILE_REQUEST = 'POST_USERPROFILE_REQUEST';
export const POST_USERPROFILE_SUCCESS = 'POST_USERPROFILE_SUCCESS';
export const POST_USERPROFILE_FAILURE = 'POST_USERPROFILE_FAILURE';

export const UPDATE_USERPROFILE_REQUEST = 'UPDATE_USERPROFILE_REQUEST';
export const UPDATE_USERPROFILE_SUCCESS = 'UPDATE_USERPROFILE_SUCCESS';
export const UPDATE_USERPROFILE_FAILURE = 'UPDATE_USERPROFILE_FAILURE';

//FLATPROFILE CONSTANTS for backend api calls
export const GET_FLATPROFILE_REQUEST = 'GET_FLATPROFILE_REQUEST';
export const GET_FLATPROFILE_SUCCESS = 'GET_FLATPROFILE_SUCCESS';
export const GET_FLATPROFILE_FAILURE = 'GET_FLATPROFILE_FAILURE';

export const POST_FLATPROFILE_REQUEST = 'POST_FLATPROFILE_REQUEST';
export const POST_FLATPROFILE_SUCCESS = 'POST_FLATPROFILE_SUCCESS';
export const POST_FLATPROFILE_FAILURE = 'POST_FLATPROFILE_FAILURE';

export const UPDATE_FLATPROFILE_REQUEST = 'UPDATE_FLATPROFILE_REQUEST';
export const UPDATE_FLATPROFILE_SUCCESS = 'UPDATE_FLATPROFILE_SUCCESS';
export const UDPATE_FLATPROFILE_FAILURE = 'UPDATE_FLATPROFILE_FAILURE';

//SET TRANSIT ATTRIBUTES
export const SET_TRANSIT_ATTRIBUTES_USERPROFILE =
    'SET_TRANSIT_ATTRIBUTES_USERPROFILE';
export const SET_TRANSIT_ATTRIBUTES_FLATPROFILE =
    'SET_TRANSIT_ATTRIBUTES_FLATPROFILE';

//UPLOAD TO FIREBASE STORAGE
export const UPLOAD_IMAGE_REQUEST_USERPROFILE =
    'UPLOAD_IMAGE_REQUEST_USERPROFILE';
export const UPLOAD_IMAGE_SUCCESS_USERPROFILE =
    'UPLOAD_IMAGE_SUCCESS_USERPROFILE';
export const UPLOAD_IMAGE_FAILURE_USERPROFILE =
    'UPLOAD_IMAGE_FAILURE_USERPROFILE';

export const UPLOAD_IMAGE_REQUEST_FLATPROFILE =
    'UPLOAD_IMAGE_REQUEST_FLATPROFILE';
export const UPLOAD_IMAGE_SUCCESS_FLATPROFILE =
    'UPLOAD_IMAGE_SUCCESS_FLATPROFILE';
export const UPLOAD_IMAGE_FAILURE_FLATPROFILE =
    'UPLOAD_IMAGE_FAILURE_FLATPROFILE';

//GENERAL
export const LOADING_STATE = 'LOADING_STATE';
